- name: Provision Macbook Pro
  hosts: hosts
  gather_facts: true

  vars:
    home: /Users/jjanzen
    user: jjanzen
    default_group: staff
    wallpaper_path: "{{ home }}/wallpaper.png"
    config_dir: "{{ home }}/.config"
    fonts_dir: "{{ home }}/Library/Fonts"
    exec_path: "{{ home }}/.local/bin"
    source_path: "{{ home }}/.local/src"
    path:
        - "{{ home }}/.cargo/bin"
        - "{{ home }}/.yarn/bin"
        - "{{ home }}/node_modules/.bin"
        - "{{ home }}/bin"
        - "{{ home }}/gems/bin"
        - "{{ home }}/.local/bin"
        - "{{ home }}/go/bin"
        - "/usr/local/bin"
        - "/Library/TeX/texbin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"

  tasks:
    - name: Create source path
      file:
        path: "{{ source_path }}"
        recurse: true
        state: directory

    - name: Configure Homebrew taps
      community.general.homebrew_tap:
        name:
          - d12frosted/emacs-plus
          - FelixKratz/formulae
          - homebrew/bundle
          - homebrew/services
          - jorgelbg/tap
          - nikitabobko/tap

    - name: Update homebrew
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true

    - name: Install basic packages
      package:
        name:
          - aescrypt
          - bash-language-server
          - bear
          - biber
          - bison
          - cabal-install
          - choose-gui
          - cmake
          - cmake-language-server
          - conan
          - curl
          - dasel
          - delta
          - dos2unix
          - eza
          - ffmpeg
          - ghc
          - gnu-tar
          - gnutls
          - go
          - gopls
          - gpgme
          - haskell-language-server
          - htop
          - hyfetch
          - imagemagick
          - inetutils
          - lesspipe
          - libassuan@2
          - marksman
          - meson
          - mpv
          - ninja
          - node
          - openjdk
          - p7zip
          - pandoc
          - pinentry-mac
          - pinentry-touchid
          - pipx
          - pkg-config
          - poppler
          - pup
          - rsync
          - rust
          - rustup
          - shellcheck
          - shfmt
          - texlive
          - typescript-language-server
          - wget
          - yaml-language-server
          - yt-dlp
          - zig
          - zlib
          - zls
          - audacity
          - blender
          - cabal
          - calibre
          - desmume
          - discord
          - dolphin
          - dwarf-fortress-lmp
          - firefox
          - gimp
          - godot
          - gzdoom
          - inkscape
          - keepingyouawake
          - krita
          - librewolf
          - multimc
          - obs
          - openemu
          - openmw
          - pokemon-showdown
          - proton-drive
          - proton-mail-bridge
          - protonvpn
          - qbittorrent
          - rar
          - thunderbird
          - tor-browser
          - vlc
          - zotero
        state: latest

    - name: Install python formatter
      community.general.pipx:
        name: black
        executable: /opt/homebrew/bin/pipx
        state: latest

    - name: Install python linter
      community.general.pipx:
        name: pylint
        state: latest
        executable: /opt/homebrew/bin/pipx

    - name: Install python lsp server
      community.general.pipx:
        name: python-lsp-server
        state: latest
        executable: /opt/homebrew/bin/pipx

    - name: Install ansible
      community.general.pipx:
        name: ansible
        state: latest
        install_deps: true
        executable: /opt/homebrew/bin/pipx

    - name: Install fonts
      import_tasks:
        file: tasks/fonts.yaml

    - name: Install common scripts
      import_tasks:
        file: tasks/common-scripts.yaml

    - name: Install app launcher script
      copy:
        src: scripts/launcher.sh
        dest: "{{ exec_path }}/launcher"
        owner: "{{ user }}"
        group: "{{ default_group }}"
        mode: "0755"

    - name: Install remove quarantine script
      copy:
        src: scripts/remove-quarantine.sh
        dest: "{{ exec_path }}/remove-quarantine"
        owner: "{{ user }}"
        group: "{{ default_group }}"
        mode: "0755"

    - name: Install and configure Aerospace
      import_tasks:
        file: tasks/aerospace.yaml

    - name: Install and configure clang-format
      import_tasks:
        file: tasks/clang-format.yaml

    - name: Install and configure Elvish
      import_tasks:
        file: tasks/elvish.yaml

    - name: Install and configure Emacs
      import_tasks:
        file: tasks/emacs.yaml

    - name: Install and configure GhosTTY
      import_tasks:
        file: tasks/ghostty.yaml

    - name: Install and configure Git
      import_tasks:
        file: tasks/git.yaml

    - name: Install and configure Kakoune
      import_tasks:
        file: tasks/kakoune.yaml

    - name: Install and configure SSH
      import_tasks:
        file: tasks/ssh.yaml

    - name: Install and configure Zellij
      import_tasks:
        file: tasks/zellij.yaml

    - name: Install and configure zsh
      import_tasks:
        file: tasks/zsh.yaml

    - name: Install the wallpaper file
      import_tasks:
        file: tasks/wallpaper.yaml

    - name: Configure macOS wallpaper
      command: osascript -e "tell application \"System Events\" to tell every desktop to set picture to \"{{ wallpaper_path }}\" as POSIX file"
      when: wallpaper.changed

    - name: Install GNU find as default find program
      file:
        src: /opt/homebrew/bin/gfind
        dest: "{{ home }}/.local/bin/find"
        owner: "{{ user }}"
        group: "{{ default_group }}"
        mode: "0755"
        state: link
