- name: Provision Asahi Linux
  hosts: hosts
  gather_facts: true
  become: true

  vars:
    home: /home/jjanzen
    user: jjanzen
    default_group: jjanzen
    wallpaper_path: "{{ home }}/.wallpaper"
    config_dir: "{{ home }}/.config"
    fonts_dir: "/usr/share/fonts"
    exec_path: "{{ home }}/.local/bin"

  tasks:
    - name: Install packages
      package:
        name:
          - bison
          - clangd
          - conan
          - foot
          - flex
          - gcc-c++
          - git-delta
          - hyfetch
          - ksshaskpass
          - libfl-devel
          - libfontenc-devel
          - libXaw-devel
          - libXcomposite-devel
          - libXcursor-devel
          - libXdmcp-devel
          - libXtst-devel
          - libXinerama-devel
          - libxkbfile-devel
          - libXrandr-devel
          - libXres-devel
          - libXScrnSaver-devel
          - xcb-util-wm-devel
          - xcb-util-image-devel
          - xcb-util-keysyms-devel
          - xcb-util-renderutil-devel
          - libXdamage-devel
          - libXxf86vm-devel
          - libXv-devel
          - xcb-util-devel
          - libuuid-devel
          - xcb-util-cursor-devel
          - mesa-libEGL-devel
          - meson
          - python3-libdnf5
          - pipx
          - sshpass
          - stack
          - systemd-devel
          - xkeyboard-config-devel
        state: latest

    - name: Install ansible
      community.general.pipx:
        name: ansible
        state: latest
        install_deps: true
        executable: /usr/bin/pipx

    - name: Install fonts
      import_tasks:
        file: tasks/fonts.yaml

    - name: Install common scripts
      import_tasks:
        file: tasks/common-scripts.yaml

    - name: Install and configure Emacs
      import_tasks:
        file: tasks/emacs.yaml

    - name: Install and configure Git
      import_tasks:
        file: tasks/git.yaml

    - name: Install and configure SSH
      import_tasks:
        file: tasks/ssh.yaml

    - name: Install and configure zsh
      import_tasks:
        file: tasks/zsh.yaml

    - name: Install the wallpaper file
      import_tasks:
        file: tasks/wallpaper.yaml
