- name: Install clang-format
  package:
    name: clang-format
    state: latest
  when: ansible_facts['os_family'] == 'Darwin'

- name: configure clang-format
  copy:
    src: config/clang-format.yaml
    dest: "{{ home }}/.clang-format"
    owner: "{{ user }}"
    group: "{{ default_group }}"
    mode: "0644"
