- name: Install Emacs required packages
  package:
    name:
      - aspell
      - autoconf
      - automake
      - findutils # TODO: make alias or something gfind -> find
      - gcc
      - gnuplot
      - hunspell
      - libgccjit
      - ripgrep

- name: Install Fedora packages
  package:
    name:
      - emacs
      - librsvg2
    state: latest
  when: ansible_facts['distribution'] == 'Fedora'

- name: Install macOS packages
  package:
    name:
      - librsvg
    state: latest
  when: ansible_facts['os_family'] == 'Darwin'
    
- name: Install Emacs
  community.general.homebrew:
    name: emacs-plus@30
    install_options:
      - with-native-comp
      - with-imagemagick
      - with-xwidgets
      - with-mailutils
      - with-ctags
      - with-retro-emacs-logo-icon
    state: latest
  when: ansible_facts['os_family'] == 'Darwin'

- name: Install Emacs configuration directory
  copy:
    src: config/emacs
    dest: "{{ config_dir }}/"
    owner: "{{ user }}"
    group: "{{ default_group }}"
