- name: Install Emacs
  community.general.homebrew:
    name: emacs-plus@30
    install_options:
      - with-native-comp
      - with-imagemagick
      - with-xwidgets
      - with-mailutils
      - with-ctags
      - with-retro-emacs-logo-icon

- name: Install Emacs configuration directory
  copy:
    src: config/emacs
    dest: "{{ config_dir }}/emacs"
    owner: "{{ user }}"
    group: "{{ default_group }}"
