- name: Install Emacs required packages
  package:
    name:
      - aspell
      - autoconf
      - automake
      - findutils # TODO: make alias or something gfind -> find
      - gcc
      - gnuplot
      - hunspell
      - libgccjit
      - isync
      - ripgrep
    state: latest

- name: Install prettier
  community.general.yarn:
    name: prettier
    global: true
    state: latest
  when: ansible_facts['distribution'] == 'Fedora'

- name: Install yaml language server
  community.general.yarn:
    name: yaml-language-server
    global: true
    state: latest
  when: ansible_facts['distribution'] == 'Fedora'

- name: Install necessary Fedora packages for Emacs
  package:
    name:
      - emacs
      - librsvg2
      - yarnpkg
    state: latest
  when: ansible_facts['distribution'] == 'Fedora'

- name: Install macOS packages
  package:
    name:
      - librsvg
      - mu
    state: latest
  when: ansible_facts['os_family'] == 'Darwin'

- name: Create ~/bin directory
  file:
    path: "{{ home }}/bin"
    recurse: true
    state: directory

- name: Install macOS Emacs
  community.general.homebrew:
    name: emacs-plus@30
    install_options:
      - with-imagemagick
      - with-xwidgets
      - with-mailutils
      - with-ctags
      - with-nobu417-big-sur-icon
    state: latest
  when: ansible_facts['os_family'] == 'Darwin'

- name: Install Emacs configuration directory
  copy:
    src: config/emacs
    dest: "{{ config_dir }}/"
    owner: "{{ user }}"
    group: "{{ default_group }}"
