- name: Install Emacs
  community.general.homebrew:
    name: emacs-plus@30
    install_options:
      - with-native-comp
      - with-imagemagick
      - with-xwidgets
      - with-mailutils
      - with-ctags
      - with-retro-emacs-logo-icon

- name: Ensure Emacs config directory exists
  file:
    path: "{{ config_dir }}/emacs"
    recurse: true
    state: directory

- name: Install Emacs early init
  copy:
    src: config/emacs-early-init.el
    dest: "{{ config_dir }}/emacs/early-init.el"
    owner: jjanzen
    group: staff
    mode: "0755"

- name: Install Emacs init
  copy:
    src: config/emacs-init.el
    dest: "{{ config_dir }}/emacs/init.el"
    owner: jjanzen
    group: staff
    mode: "0755"

- name: Install Emacs RSS feed
  copy:
    src: config/emacs-feed.el
    dest: "{{ config_dir }}/emacs/feed.el"
    owner: jjanzen
    group: staff
    mode: "0755"
