- name: Install git
  package:
    name: git
    state: latest

- name: Ensure git config dir exists
  file:
    path: "{{ config_dir }}/git"
    recurse: true
    state: directory

- name: Configure git
  copy:
    src: config/git.ini
    dest: "{{ config_dir }}/git/config"
    owner: "{{ user }}"
    group: "{{ default_group }}"
    mode: "0644"
