- name: Install river
  package:
    name:
      - river
      - brightnessctl
      - dunst
      - fuzzel
      - grim
      - libinput-devel
      - NetworkManager-tui
      - pamixer
      - slurp
      - swayidle
      - swaylock
      - waybar
      - wayland-devel
      - wlr-randr
      - yaml-cpp-devel
    state: latest

- name: Dowload way-displays source
  get_url:
    url: https://github.com/alex-courtis/way-displays/archive/refs/tags/1.14.0.tar.gz
    dest: /usr/local/src/way-displays.tar.gz
  register: way_displays_source_download

- name: Unpack way-displays source
  unarchive:
    src: /usr/local/src/way-displays.tar.gz
    dest: /usr/local/src
  when: way_displays_source_download.changed
  register: way_displays_source_unpack

- name: Compile and install way-displays source
  community.general.make:
    chdir: /usr/local/src/way-displays-1.14.0/
    target: install
  when: way_displays_source_unpack.changed

- name: Create river configuration directory
  file:
    path: "{{ config_dir }}/river"
    recurse: true
    state: directory
    owner: "{{ user }}"
    group: "{{ default_group }}"

- name: Create river init script
  copy:
    src: config/river/init
    dest: "{{ config_dir }}/river/init"
    owner: "{{ user }}"
    group: "{{ default_group }}"
    mode: "0755"
