- name: Install SketchyBar
  package:
    name:
      - sketchybar
      - font-hack-nerd-font
    state: latest

- name: Ensure SketchyBar config directory exists
  file:
    path: "{{ config_dir }}/sketchybar/plugins"
    recurse: true
    state: directory
