- name: Install packages necessary for zsh
  package:
    name:
      - zsh
    state: latest

- name: Setup zsh package directory
  file:
    path: "{{ home }}/.zsh"
    recurse: true
    state: directory

- name: Install zsh autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ home }}/.zsh/zsh-autosuggestions"

- name: Install zsh syntax highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting
    dest: "{{ home }}/.zsh/zsh-syntax-highlighting"

- name: Configure zsh
  copy:
    src: config/zshrc.sh
    dest: "{{ home }}/.zshrc"
    owner: "{{ user }}"
    group: "{{ default_group }}"
    mode: "0755"

- name: Configure shell profile
  template:
      src: config/profile.sh.j2
      dest: "{{ home }}/.zshenv"
      owner: "{{ user }}"
      group: "{{ default_group }}"
      mode: "0755"
