#+title: Waybar Styling
Set global font, colours, and transitions to have a transparent background. The text is white with a small shadow.
#+begin_src css :tangle ~/.config/waybar/style.css :mkdirp yes
  window#waybar {
      font-family: FontAwesome, Roboto, Helvetica, Arial, sans-serif;
      font-size: 13px;
      background: transparent;
      color: #ffffff;
      text-shadow: 1px 1px #64727D;
      transition-property: background-color;
      transition-duration: .5s;
  }
#+end_src

Remove the border from buttons and make them square.
#+begin_src css :tangle ~/.config/waybar/style.css :mkdirp yes
  button {
      border: none;
      border-radius: 0;
  }
#+end_src

Hovering over a button should inherit the background colour and add a white border to the bottom.
#+begin_src css :tangle ~/.config/waybar/style.css :mkdirp yes
  button:hover {
      background: inherit;
      box-shadow: inset 0 -3px #ffffff;
  }
#+end_src

Workspace buttons should have white with a small shadow, a little bit of extra horizontal padding, and a transparent background.
#+begin_src css :tangle ~/.config/waybar/style.css :mkdirp yes
  #workspaces button {
      padding: 0 5px;
      text-shadow: 1px 1px #64727D;
      background-color: transparent;
      color: #ffffff;
  }
#+end_src

Hovering over a workspace button should darken it.
#+begin_src css :tangle ~/.config/waybar/style.css :mkdirp yes
  #workspaces button:hover {
      background: rgba(0, 0, 0, 0.2);
  }
#+end_src

The focused workspace should have a white bottom border.
#+begin_src css :tangle ~/.config/waybar/style.css :mkdirp yes
  #workspaces button.focused {
      background: transparent;
      box-shadow: inset 0 -3px #ffffff;
  }
#+end_src

Urgent workspaces should be red.
#+begin_src css :tangle ~/.config/waybar/style.css :mkdirp yes
  #workspaces button.urgent {
      background-color: #eb4d4b;
  }
#+end_src

Add extra horizontal padding where needed.
#+begin_src css :tangle ~/.config/waybar/style.css :mkdirp yes
  #clock,
  #cpu,
  #memory,
  #disk,
  #network,
  #pulseaudio,
  #wireplumber,
  #custom-media,
  #tray,
  #mode,
  #scratchpad,
  #mpd {
      padding: 0 10px;
  }
#+end_src

Add extra horizontal margins where needed.
#+begin_src css :tangle ~/.config/waybar/style.css :mkdirp yes
  #window,
  #workspaces {
      margin: 0 4px;
  }
#+end_src

Omit margins on the leftmost and rightmost workspaces.
#+begin_src css :tangle ~/.config/waybar/style.css :mkdirp yes
  .modules-left > widget:first-child > #workspaces {
      margin-left: 0;
  }

  /* If workspaces is the rightmost module, omit right margin */
  .modules-right > widget:last-child > #workspaces {
      margin-right: 0;
  }
#+end_src

Passive system tray icons are dimmed.
#+begin_src css :tangle ~/.config/waybar/style.css :mkdirp yes
  #tray > .passive {
      -gtk-icon-effect: dim;
  }
#+end_src

Tray icons that need attention are highlighted.
#+begin_src css :tangle ~/.config/waybar/style.css :mkdirp yes
  #tray > .needs-attention {
      -gtk-icon-effect: highlight;
  }
#+end_src

The scratchpad should be darkened and transparent when empty.
#+begin_src css :tangle ~/.config/waybar/style.css :mkdirp yes
  #scratchpad {
      background: rgba(0, 0, 0, 0.2);
  }

  #scratchpad.empty {
      background-color: transparent;
  }
#+end_src
