#+title: River Configuration

This is literally just a shell script.
#+begin_src sh
  #!/bin/sh
#+end_src

Start a terminal with =super+return=.
#+begin_src sh
  riverctl map normal Super Return spawn foot
#+end_src

Start an application launcher with =super+d=.
#+begin_src sh
  riverctl map normal Super D spawn fuzzel
#+end_src

Take a screenshot with =super+shift+s=.
#+begin_src sh
  riverctl map normal Super+Shift S spawn 'grim -g "$(slurp)" - | wl-copy'
#+end_src

Lock the screen with =super+control+q=.
#+begin_src sh
  riverctl map normal Super+Control Q spawn 'swaylock -c 008080'
#+end_src

Close an application with =super-q=.
#+begin_src sh
  riverctl map normal Super Q close
#+end_src

Log out with =super+shift+e=.
#+begin_src sh
  riverctl map normal Super+Shift E exit
#+end_src

Move to the next/previous view with =super+j/k=.
#+begin_src sh
  riverctl map normal Super J focus-view next
  riverctl map normal Super K focus-view previous
#+end_src

Swap positions of the current view with the next/previous with =super+shift+j/k=.
#+begin_src sh
  riverctl map normal Super+Shift J swap next
  riverctl map normal Super+Shift K swap previous
#+end_src

Focus on the next/previous output with =super+period/comma=.
#+begin_src sh
  riverctl map normal Super Period focus-output next
  riverctl map normal Super Comma focus-output previous
#+end_src

Send the focused view to the next/previous output with =super+shift+period/comma=.
#+begin_src sh
  riverctl map normal Super+Shift Period send-to-output next
  riverctl map normal Super+Shift Comma send-to-output previous
#+end_src

Move the focused view to the top of the layout stack with =super+shift+return=.
#+begin_src sh
  riverctl map normal Super+Shift Return zoom
#+end_src

Decrease/increase the main ratio main ratio of rivertile with =super+h/l=.
#+begin_src sh
  riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
  riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"
#+end_src

Increment/decrement the main count of rivertile with =super+shift+h/l=.
#+begin_src sh
  riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
  riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"
#+end_src

Move a view with =super+alt+h/j/k/l=.
#+begin_src sh
  riverctl map normal Super+Alt H move left 100
  riverctl map normal Super+Alt J move down 100
  riverctl map normal Super+Alt K move up 100
  riverctl map normal Super+Alt L move right 100
#+end_src

Snap a view with =super+alt+ctrl+h/j/k/l=.
#+begin_src sh
  riverctl map normal Super+Alt+Control H snap left
  riverctl map normal Super+Alt+Control J snap down
  riverctl map normal Super+Alt+Control K snap up
  riverctl map normal Super+Alt+Control L snap right
#+end_src

Resize a view with =super+alt+shift+h=.
#+begin_src sh
  riverctl map normal Super+Alt+Shift H resize horizontal -100
  riverctl map normal Super+Alt+Shift J resize vertical 100
  riverctl map normal Super+Alt+Shift K resize vertical -100
  riverctl map normal Super+Alt+Shift L resize horizontal 100
#+end_src

Allow mouse controls with the =super= key. Left mouse moves, right mouse resizes, and middle toggles floating mode.
#+begin_src sh
  riverctl map-pointer normal Super BTN_LEFT move-view
  riverctl map-pointer normal Super BTN_RIGHT resize-view
  riverctl map-pointer normal Super BTN_MIDDLE toggle-float
#+end_src

Use natural scrolling on the MacBook Pro TrackPad.
#+begin_src sh
  riverctl input pointer-1452-850-Apple_MTP_multi-touch natural-scroll disabled
#+end_src

Manage tags. =super+#= moves focus to tag =#=. =super+shift+#= changes the tag of the focused view to =#=. Adding =ctrl= to either of these toggles rather than moving.
#+begin_src sh
  for i in $(seq 1 9)
  do
      tags=$((1 << ($i - 1)))
      riverctl map normal Super $i set-focused-tags $tags
      riverctl map normal Super+Shift $i set-view-tags $tags
      riverctl map normal Super+Control $i toggle-focused-tags $tags
      riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
  done
#+end_src

=super+0= focuses all tags and =super+shift+0= assigns the focused view to all tags.
#+begin_src sh
  all_tags=$(((1 << 32) - 1))
  riverctl map normal Super 0 set-focused-tags $all_tags
  riverctl map normal Super+Shift 0 set-view-tags $all_tags
#+end_src

Toggle float mode with =super+space=.
#+begin_src sh
  riverctl map normal Super Space toggle-float
#+end_src

Toggle fullscreen mode with =super+f=.
#+begin_src sh
  riverctl map normal Super F toggle-fullscreen
#+end_src

Change the layout orientation with =super+up/right/down/left=.
#+begin_src sh
  riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
  riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
  riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
  riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"
#+end_src

Configure media keys.
#+begin_src sh
  for mode in normal locked
  do
      riverctl map $mode None XF86Eject spawn 'eject -T'
      riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
      riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
      riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'
      riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
      riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
      riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
      riverctl map $mode None XF86AudioNext  spawn 'playerctl next'
      riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
      riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
  done
#+end_src

Configure colours.
#+begin_src sh
  riverctl background-color 0x008080
  riverctl border-color-focused 0xc3c3c3
  riverctl border-color-unfocused 0x818181
#+end_src

Set key repeat.
#+begin_src sh
  riverctl set-repeat 50 300
#+end_src

Start river with tiling.
#+begin_src sh
  riverctl default-layout rivertile
  rivertile -view-padding 6 -outer-padding 6 &
#+end_src

Start KDE Connect at login.
#+begin_src sh
  kdeconnectd > /tmp/kdeconnect.${USER}.log 2>&1 &
#+end_src

Start notification manager.
#+begin_src sh
  dunst &
#+end_src

Start waybar.
#+begin_src sh
  waybar &
#+end_src

Start Wi-Fi connection.
#+begin_src sh
  nm-applet &
#+end_src

Configure displays automatically.
#+begin_src sh
  way-displays > /tmp/way-displays.${XDG_VTNR}.${USER}.log 2>&1 &
#+end_src
